name: Q1 Workflow
on: [push]
jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Copy README.md to Q1_archive_README.md
        run: cp README.md Q1_archive_README.md
      - name: Push changes
        run: |
          git config --global user.name "TomGoureau"
          git config --global user.email "tom.goureau@gmail.com"
          cp README.md Q1_archive_README.md
          git add Q1_archive_README.md
          git commit -m "Add Q1_archive_README.md"
          git push
