name: Q2 Workflow
on: [push]
jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Q2_archive_README.md
        run: |
          echo "GOUREAU Tom" > Q2_archive_README.md
          date >> Q2_archive_README.md
          cat README.md >> Q2_archive_README.md
      - name: Push changes
        run: |
          git config --global user.name "Tom"
          git config --global user.email "tom.goureau@etu.univ-lehavre.fr"
          git add Q2_archive_README.md
          git commit -m "Add Q2_archive_README.md"
          git push
